---
- hosts: all
  remote_user: root

  tasks:
    - name: get hostname
      command: /bin/hostname
      changed_when: False
      register: hostname

    - name: get uptime
      command: /usr/bin/uptime
      changed_when: False
      register: uptime

    - debug: var={{ item }}
      with_items:
        - hostname.stdout
        - uptime.stdout
