all:
  vars:
    ansible_user: pi
  children:
    master:
      hosts:
        kube-master:
          ansible_port: 2220
          ansible_host: 192.168.236.50
    nodes:
      hosts:
        kube-node-1:
          ansible_port: 2221
          ansible_host: 192.168.236.50
        kube-node-2:
          ansible_port: 2222
          ansible_host: 192.168.236.50
        kube-node-3:
          ansible_port: 2223
          ansible_host: 192.168.236.50
        kube-node-4:
          ansible_port: 2224
          ansible_host: 192.168.236.50
